language: php
php:
  - '7.2'
  - '7.1'

branches:
  only:
    - master

install:
  - travis_retry pecl install redis
  - travis_retry composer install --no-interaction

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - export CODECOV_TOKEN="24382d15-84e7-4a55-bea4-c4df96a24a9b"
  - bash <(curl -s https://codecov.io/bash)